Remove Invest_Applet.xml from po/POTFILES.in
It causes gettext to throw a fit and mateweather applet has a simular
file and it is also not in POTFILES.in

The error it throws is:
junk after document element at line 2, column 0, byte 45 at
/usr/lib64/perl5/vendor_perl/5.16.3/x86_64-linux/XML/Parser.pm line 187.
/usr/bin/xgettext: error while opening
"../invest-applet/data/Invest_Applet.xml.h" for reading: No such file or
directory
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.